## Follow the repository's Code Tour for configuration. Threshold: 8%

name: Images Build and Scan

on:
  push:
    branches:
      - "**"       

jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  brand_profile_upsert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          path: main
          files: |
             ./main/gitops/edge-manager/local/**

      - name: List all changed files
        run: |
          mkdir ~/myfiles 
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            pwd
            ls
            cp main/$file ~/myfiles
          done
          echo "myfiles are : "
          ls ~/myfiles
